services:
  teralux-backend:
    image: ghcr.io/pt-perkasa-pilar-utama/teralux-backend:latest
    container_name: teralux-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
    restart: unless-stopped